module.exports = Object.freeze({
  // AUTH (Who you are, and getting logged in)
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  AUTHORIZATION_FAILURE: 'AUTHORIZATION_FAILURE',
  INVALID_PASSWORD_UPDATE_CONTEXT: 'INVALID_PASSWORD_UPDATE_CONTEXT',

  // INPUT (The data the client sent)
  INVALID_INPUT: 'INVALID_INPUT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  DUPLICATE_VALUE: 'DUPLICATE_VALUE',

  // REQUEST (The request itself, before your logic runs)
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',

  // SERVER (Something on your side)
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNSPECIFIED_ERROR: 'UNSPECIFIED_ERROR',
});